### ISSUE TITLE
Error on latest neovim master

### ISSUE THREAD

**Issue by Shatur** [steelsojka/completion-buffers#11]
After neovim update I experiencing the following error:

```
|| Error detected while processing
pack\plugins\opt\completion-buffers\after\plugin\completion_buffers.vim|1| 
|| E5108: Error executing lua ...ack\plugins\opt\completion-nvim\lua\completion\hover.lua:250: attempt to index field 'handlers' (a nil value)
```

**Comment by steelsojka** [comment]
I don't think this is an issue with this plugin. I ran into the same with my nvim locally. If you look at the stack trace the issue is in completion-nvim, not this source. Try updating all the plugins after the update.
