### ISSUE TITLE
How to configure? LSP should be working but buffer completions

### ISSUE THREAD

**Issue by thepenguinthatwants** [steelsojka/completion-buffers#12]
Hi!
Is this meant to work that it gives completions on words from buffers.

I added this to my init.vim and installed using vim-plug.

```
Plug 'neovim/nvim-lspconfig'
Plug 'nvim-lua/completion-nvim'
Plug 'steelsojka/completion-buffers'
```

```
:lua << EOF
completion_chain_complete_list = {
  { complete_items = { 'lsp' } },
  { complete_items = { 'buffers' } },
  { mode = { '<c-p>' } },
  { mode = { '<c-n>' } }
}
EOF
```

But it doesnt give any options from normal buffers. I've set lsp to work with python and it works so I am wondering if I've misunderstood how to configure this.

**Comment by steelsojka** [comment]
@thepenguinthatwants how are you configuring the completion plugin? You can't run the command and have that configuration take effect. You'll need to put the configuration in your init.vim or in once of your start up files. I'm gonna close this since it's a configuration error and not an issue with this plugin source. but feel free to keep discussing the configuration so we can try and solve it.

**Comment by thepenguinthatwants** [comment]
Thanks, I am wondering how to add that onto my init.vim

I tried adding this but it didnt work.

let g:completion_chain_complete_list = 'buffers'

**Comment by delphinus** [comment]
@thepenguinthatwants I fixed README in #14. See that.

**Comment by thepenguinthatwants** [comment]
Oooh now I get it sorry,
I left out 

    { mode = { '<c-p>' } },
    { mode = { '<c-n>' } }

this earlier```

as I  have this and thought that using tab I could get the autocompletion list.
```
inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
```

Altho this didnt work nor the one below

```
vim.g.completion_chain_complete_list = {
  default = {
    { complete_items = { 'lsp' } },
    { complete_items = { 'buffers' } },
    { mode = { '<Tab>' } },
    { mode = { '<S-Tab>' } }
  },
}
```

Any way to make it automatically add a completion list instead of using <c-p> keybinding?

**Comment by delphinus** [comment]
@thepenguinthatwants 
I'm afraid you misunderstand the mean of `mode` properties. The values of `mode` should be kinds of `ins-complete`. (See `:h ins-complete`) That is, `"<c-p>"` and `"<c-n>"` are not the keys itself. They mean completion chain succeeds with candidates from `i_CTRL-N`, `i_CTRL-P`.

All you can set for `mode` props are described [here][].

[here]: https://github.com/nvim-lua/completion-nvim/blob/fc9b2fd2d47bea6a8954de1b1b19f2330545b354/doc/completion-nvim.txt#L245-L259

**Comment by thepenguinthatwants** [comment]
Oh okay, sorry I guess I misunderstood how this completion worked.
I thought this uses buffer as a source and could show autocomplete list automatically.
