### ISSUE TITLE
[Feature request] Ignore words in comments

### ISSUE THREAD

**Issue by quantum-booty** [steelsojka/completion-buffers#13]
If I have a lot comments then it pollutes the completion, by ignoring the comments the autocompletion is more accurate.

**Comment by steelsojka** [comment]
Thanks for the request! I don't think this completion source should concern itself with what is "code" vs a "comment". This just simply extracts words from buffers. You can fine tune how words are extracted through a regex but I don't think that would be enough to distinguish, reliably, words in a comment. I think the lsp source or the treesitter source would be a better source for more "source code aware" results.
