### ISSUE TITLE
Not completing words with extended latin characters

### ISSUE THREAD

**Issue by boydkelly** [steelsojka/completion-buffers#16]
Since doing a lot of work with extended latin characters, I notice that lua lsp buffer completion is not working with these.   The characters I am working with are indicated below.  Please note that these characters are available on a wide variety of terminal fonts for example adobe-code-pro, cousine, notosans, déjavu, etc, 

I have checked with neovim nightly with zero configuration, and the regular ctrl-p tab will complete words with those characters.

If I have only the words 'mɔgɔ' and 'test' in my file and on a new line i type m, press ctrl-p and tab with regular completion the word mɔgɔ will be completed.   However with lsp buffer completion, there is is menu of course but the word is not listed.

File contents:
````
mɔgɔ
test
````

(after pressing ctrl-p the completion menu is as follows:)

````
mailto            Email 
mailto UltiSnips 
menu   UltiSnips 
test   Buffers   

````
Config snippet
````
  local opts = { noremap=true, silent=true }    
  vim.o.shortmess = vim.o.shortmess .. 'c'
  vim.o.completeopt = 'menuone,noinsert,noselect'
  vim.g.completion_enable_auto_popup = 0
 
  vim.g.completion_matching_strategy_list = {'exact', 'substring', 'fuzzy', 'all'}
  vim.g.completion_enable_snippet = 'UltiSnips'
  
  -- Chain completion list
  vim.g.completion_chain_complete_list = {
    default = {
      default = {
        { complete_items = { 'lsp', 'snippet', 'buffers' }},
        { mode = '<c-p>'},
        { mode = '<c-n>'}},
      comment = {},
      string = { { complete_items = { 'path' }} }}  
  }

````

keymap file for reference:
````
let b:keymap_name="dyu"    
    
highlight lCursor ctermbg=red guibg=red    
                                                                                                                                                 
loadkeymap    
    
;o> ɔ>"0254    
;O> Ɔ>"0186    
;e> ɛ>"025B    ``
;E> Ɛ>"0190>    
;n> ɲ>"0272    
;N> Ɲ>"019D-    
;g> ŋ>"014B    
;G> Ŋ>"014A   
````

**Comment by steelsojka** [comment]
There is a configuration that defines what pattern makes a word. You should
be able to adjust this to support what you want. Im on mobile right now, so
im not sure what the variable is at the moment.

**Comment by boydkelly** [comment]
ok got it!  Thanks, it was in plain sight.  

````
let g:completion_word_separator = "[^ɛƐɔƆɲƝŋŊa-zA-Z0-9\-_]"
````
