### ISSUE TITLE
Current word under cursor appears in the completion list

### ISSUE THREAD

**Issue by steelsojka** [steelsojka/completion-buffers#4]
This is annoying... fix it

**Comment by haorenW1025** [comment]
I've noticed [asyncomplete-buffers](https://github.com/prabirshrestha/asyncomplete-buffer.vim) has a interesting feature which add words to current buffers incrementally and also avoid adding words under current cursor. May be a good reference to this issue.

**Comment by steelsojka** [comment]
I excluded including the prefix in the list and that fixes the issue. Let me know if there are other scenarios that his may occur during.
