### ISSUE TITLE
g:completion_trigger_on_delete=0 is not respected

### ISSUE THREAD

**Issue by astier** [steelsojka/completion-buffers#6]
Hallo. It seems that completion-buffers does not respect the setting `g:completion_trigger_on_delete = 0`. With the following minimal vimrc the buffer-source triggers completion when deleting characters with `<bs>`. The path-source however does not trigger completion.

```vim
cal plug#begin($XDG_DATA_HOME.'/nvim/plugins')
    Plug 'nvim-lua/completion-nvim'
    Plug 'steelsojka/completion-buffers'
cal plug#end()

au bufenter * lua require'completion'.on_attach()
let g:completion_auto_change_source = 1
let g:completion_trigger_on_delete = 0
let g:completion_chain_complete_list = [
    \{ 'complete_items': ['path'] },
    \{ 'complete_items': ['buffer'] },
\]
se completeopt=menuone,noinsert
```

**Comment by steelsojka** [comment]
I don't think this an issue with the source. The source doesn't trigger when completion is shown. This would be an issue with completion-nvim.
