### ISSUE TITLE
Respect chain completion settings when caching results

### ISSUE THREAD

**Issue by kristijanhusak** [steelsojka/completion-buffers#8]
Currently, all buffers are being cached. It would be good to respect chain completion settings when caching.

For example, If i have this chain completion settings:
```vimL
let g:completion_chain_complete_list = {
      \ 'log': [
      \   {'mode': '<c-n>'},
      \],
      \ 'default': [
      \    {'complete_items': ['lsp']},
      \    {'complete_items': ['buffers']},
      \  ]}

```

I don't want to have buffers completion for log filetype, thus it shouldn't even do any caching for it.
This is especially problematic with big log files, since it caches the whole thing, and freezes neovim for several seconds, or more, depending on file size.

**Comment by steelsojka** [comment]
Hmmm... I don't think we have enough information through the API to know where the source lives in the chain of completion sources. Right now it caches on `BufEnter`. We could cache only when the source is triggered for a certain buffer (I'm not sure if we have the specific buffer that was triggered) but it will slow down the initial completion and require us to manage an attachment to the buffer.

The other option is just having certain filetypes ignored by the source to avoid having those files cached... This seems like the easier solution and solves your issue.

**Comment by kristijanhusak** [comment]
I guess we could iterate through it and see if it's defined. It's a bit problematic since this can be both dictionary and list. Defining simple list of ignored filetypes would also do the trick, and is indeed much simpler.

**Comment by steelsojka** [comment]
@kristijanhusak Can you confirm if this was fixed in the latest release using the `g:completion_word_ignored_ft` option?

**Comment by kristijanhusak** [comment]
@steelsojka It's working, thanks!
